#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "chtickynotes"
name = "ChtickyNotes"
description.en = "Generic sticky notes for all purpose"
description.fr = "Post-its génériques à tout faire"

version = "1.0~ynh6"

maintainers = []

[upstream]
license = "MIT"
code = "https://github.com/YunoHost-Apps/chtickynotes_ynh/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false # TODO:
sso = false # TODO:
disk = "10M"
ram.build = "50M"
ram.runtime = "10M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/chtickynotes"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php7.4-fpm",
    ]
