#!/bin/bash
app=chtickynotes

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)

# Remove sources
sudo rm -rf /var/www/$app

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
